version: '3.9'

services:
    nginx:
        container_name: nginx
        build:
            context: req/nginx
            dockerfile: Dockerfile
        depends_on:
            - wordpress
        image: nginx:hbelhadj
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/html
        networks:
            - anternit
        restart: always

    mariadb:
        build:
            context: req/mariadb
            dockerfile: Dockerfile
        restart: always
        container_name: mariadb
        image: mariadb:hbelhadj
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - anternit
        env_file:
            - ./.env

    wordpress:
        build:
            context: req/wordpress
            dockerfile: Dockerfile
        restart: always
        container_name: wordpress
        image: wordpress:hbelhadj
        volumes:
            - wordpress:/var/www/html
        networks:
            - anternit
        depends_on:
            - mariadb
        env_file:
            - ./.env

networks:
    anternit: {}
  
volumes:
    wordpress:
        driver: local
        driver_opts:
            type: none
            device: '/home/haitam/data/wp'
            o: 'bind'
    mariadb:
        driver: local
        driver_opts:
            type: none
            device: '/home/haitam/data/db'
            o: 'bind'
